"""Tests for the depends_on line in planner-generated sub-issue bodies.

The planner's _sub_issue_body must include a `depends_on:` line in EVERY
sub-issue body — empty for leaf tasks, listing prerequisites for dependent
tasks. These tests verify both the formatting and parseability.
"""
from __future__ import annotations

import sys
from pathlib import Path
from unittest.mock import MagicMock

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core.iterate import _sub_issue_body  # noqa: E402
from core.providers.base import parse_depends_on  # noqa: E402


def test_leaf_task_has_empty_depends_on_line():
    """Task with no dependencies must emit an empty 'depends_on:' line."""
    body = _sub_issue_body(
        parent_n=42,
        parent_title="Test Epic",
        scope="Do something",
        depends_on=[],
    )
    # Must contain the depends_on: line
    assert "depends_on:" in body
    # The line should be blank after the colon (no issue references)
    lines = body.splitlines()
    dep_lines = [l for l in lines if l.startswith("depends_on:")]
    assert len(dep_lines) == 1
    line = dep_lines[0]
    # After "depends_on:" there should be nothing (empty) or whitespace
    after_colon = line.split(":", 1)[1].strip()
    assert after_colon == ""


def test_single_dependency_formatting():
    """Task with one prerequisite must list it: depends_on: #N."""
    body = _sub_issue_body(
        parent_n=42,
        parent_title="Test Epic",
        scope="Do something",
        depends_on=[10],
    )
    assert "depends_on: #10" in body
    lines = body.splitlines()
    dep_lines = [l for l in lines if l.startswith("depends_on:")]
    assert len(dep_lines) == 1


def test_multiple_dependencies_formatting():
    """Task with multiple prerequisites must list them comma-separated."""
    body = _sub_issue_body(
        parent_n=42,
        parent_title="Test Epic",
        scope="Do something",
        depends_on=[10, 20, 30],
    )
    assert "depends_on: #10, #20, #30" in body
    lines = body.splitlines()
    dep_lines = [l for l in lines if l.startswith("depends_on:")]
    assert len(dep_lines) == 1


def test_depends_on_line_before_scope_section():
    """depends_on: line must appear between backlink and ## Scope."""
    body = _sub_issue_body(
        parent_n=42,
        parent_title="Test Epic",
        scope="Do something",
        depends_on=[10, 20],
    )
    lines = body.splitlines()
    dep_idx = next(i for i, l in enumerate(lines) if l.startswith("depends_on:"))
    scope_idx = next(i for i, l in enumerate(lines) if l == "## Scope")
    backlink_idx = next(i for i, l in enumerate(lines) if l.startswith("Part of epic"))
    assert backlink_idx < dep_idx < scope_idx


def test_depends_on_parsed_correctly_empty():
    """parse_depends_on must return [] for an empty depends_on: line."""
    body = _sub_issue_body(42, "Epic", "scope", depends_on=[])
    deps = parse_depends_on(body)
    assert deps == []


def test_depends_on_parsed_correctly_single():
    """parse_depends_on must extract the single issue number."""
    body = _sub_issue_body(42, "Epic", "scope", depends_on=[10])
    deps = parse_depends_on(body)
    assert deps == [10]


def test_depends_on_parsed_correctly_multiple():
    """parse_depends_on must extract all issue numbers in order."""
    body = _sub_issue_body(42, "Epic", "scope", depends_on=[10, 20, 30])
    deps = parse_depends_on(body)
    assert deps == [10, 20, 30]


def test_body_still_has_required_sections():
    """Smoke test: the refactor must not remove standard template sections."""
    body = _sub_issue_body(42, "Epic", "scope", depends_on=[])
    assert "Part of epic #42" in body
    assert "## Scope" in body
    assert "## Acceptance Criteria" in body
    assert "## Notes" in body
    assert "Auto-generated by Daedalus" in body
